/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.CH_gui.dialog;

/**
 * Copyright 2001-2013 CryptoHeaven Corp. All Rights Reserved.
 *
 * @author  Marcin Kurzawa
 */
public class ChatSessionChooserPanel extends javax.swing.JPanel {

  /**
   * Creates new form ChatSessionChooserPanel
   */
  public ChatSessionChooserPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jNote1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        contact1 = new javax.swing.JLabel();
        contact2 = new javax.swing.JLabel();
        contact3 = new javax.swing.JLabel();
        contact4 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jNote3 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabelMore = new javax.swing.JLabel();
        jLabelPerfectMatch = new javax.swing.JLabel();
        jUpdate1 = new javax.swing.JLabel();
        jUpdate2 = new javax.swing.JLabel();
        jUpdate3 = new javax.swing.JLabel();
        jUpdate4 = new javax.swing.JLabel();
        jUpdate5 = new javax.swing.JLabel();
        jUpdate6 = new javax.swing.JLabel();
        jUpdate7 = new javax.swing.JLabel();
        jUpdate8 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(153, 153, 153));

        jNote1.setText("Selected contacts for this chat session are:");

        contact1.setText("Jonny");

        contact2.setText("Fred");

        contact3.setText("Henry");

        contact4.setText("and 3 more...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(contact1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contact2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contact3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contact4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(contact1)
                .addComponent(contact2)
                .addComponent(contact3)
                .addComponent(contact4))
        );

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-48.png"))); // NOI18N

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chat-group-48.png"))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Private session between selected contacts only.");
        jRadioButton1.setActionCommand("");

        jNote3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNote3.setText("Open existing group session:");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Focus Group, Adas, Henry");
        jRadioButton2.setActionCommand("");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Department");
        jRadioButton3.setActionCommand("");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Other group session");
        jRadioButton4.setActionCommand("");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Another session");
        jRadioButton5.setActionCommand("");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Yet another session");
        jRadioButton6.setActionCommand("");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Almost last session");
        jRadioButton7.setActionCommand("");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Last");
        jRadioButton8.setActionCommand("");

        jLabelMore.setText("More options are available under Instant Message History");

        jLabelPerfectMatch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPerfectMatch.setText("Private chat:");

        jUpdate1.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate1.setText("Last Stamp");

        jUpdate2.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate2.setText("jLabel2");

        jUpdate3.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate3.setText("jLabel3");

        jUpdate4.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate4.setText("jLabel4");

        jUpdate5.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate5.setText("jLabel5");

        jUpdate6.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate6.setText("jLabel6");

        jUpdate7.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate7.setText("jLabel7");

        jUpdate8.setForeground(new java.awt.Color(153, 153, 153));
        jUpdate8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon1)
                            .addComponent(icon2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPerfectMatch)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jNote3)
                            .addComponent(jLabelMore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUpdate1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUpdate8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNote1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNote1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPerfectMatch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jUpdate1)))
                    .addComponent(icon1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNote3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jUpdate2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jUpdate3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4)
                            .addComponent(jUpdate4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton5)
                            .addComponent(jUpdate5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton6)
                            .addComponent(jUpdate6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton7)
                            .addComponent(jUpdate7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton8)
                            .addComponent(jUpdate8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMore))
                    .addComponent(icon2))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JLabel contact1;
    protected javax.swing.JLabel contact2;
    protected javax.swing.JLabel contact3;
    protected javax.swing.JLabel contact4;
    protected javax.swing.JLabel icon1;
    protected javax.swing.JLabel icon2;
    protected javax.swing.JLabel jLabelMore;
    protected javax.swing.JLabel jLabelPerfectMatch;
    private javax.swing.JLabel jNote1;
    private javax.swing.JLabel jNote3;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JRadioButton jRadioButton1;
    protected javax.swing.JRadioButton jRadioButton2;
    protected javax.swing.JRadioButton jRadioButton3;
    protected javax.swing.JRadioButton jRadioButton4;
    protected javax.swing.JRadioButton jRadioButton5;
    protected javax.swing.JRadioButton jRadioButton6;
    protected javax.swing.JRadioButton jRadioButton7;
    protected javax.swing.JRadioButton jRadioButton8;
    protected javax.swing.JLabel jUpdate1;
    protected javax.swing.JLabel jUpdate2;
    protected javax.swing.JLabel jUpdate3;
    protected javax.swing.JLabel jUpdate4;
    protected javax.swing.JLabel jUpdate5;
    protected javax.swing.JLabel jUpdate6;
    protected javax.swing.JLabel jUpdate7;
    protected javax.swing.JLabel jUpdate8;
    // End of variables declaration//GEN-END:variables
}
